name: Publish Desktop Application

on:
  push:
  pull_request:
    tags:
    - "v*"
jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: MarkIt.sln                                 # Replace with your solution name, i.e. MyWpfApp.sln.
      Wap_Project_Directory: MarkItDesktop                      # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: MarkItDesktop\MarkItDesktop.csproj      # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore solution
      run: dotnet restore ${{ env.Solution_Name }}
    
    - name: Publish Application
      run: dotnet publish ${{ env.Wap_Project_Directory }} -r win-x64 -c Release --self-contained --no-restore
      
    - name: Compress Application Files
      run: 7z a Release.zip ${{ env.Wap_Project_Directory }}\bin\Release\net6.0-windows\win-x64\publish
      
    - name: Upload archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.zip
        asset_name: MarkIt $tag
        tag: ${{ github.ref }}
        overwrite: true
